CREATE TABLE IF NOT EXISTS BREEDS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DOGS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DOG_NAME VARCHAR(30) NOT NULL,
    OWNER_NAME VARCHAR(30) NOT NULL,
    AGE INTEGER NOT NULL,
    BREED_ID INTEGER REFERENCES BREEDS(ID)

        CONSTRAINT AGE_CHECK CHECK (AGE >= 1 AND AGE < 15)
);